/**
 * Favorite matcha spots for the map. Edit freely.
 * Loaded as a classic script so window.MATCHA_PLACES is available globally.
 * Map markers rotate 3 illustrations (cup, iced latte, bowl); optional per-place
 * icon: pin-cup | pin-latte | pin-bowl to pin a specific art.
 * Mock US + Tokyo cafes below are placeholder coordinates for previews.
 */
window.MATCHA_PLACES = [

  {
    id: "ippodo-kyoto",
    name: "Ippodo Tea",
    city: "Kyoto",
    country: "Japan",
    lat: 35.0116,
    lng: 135.7681,
    rating: 4.9,
    tagline: "quiet ceremony & the best usucha",
    note: "Centuries of ritual seem to steep in every bowl, as though the city’s quiet dignity had been whisked into green foam.",
    signatureDrink: "Usucha",
  },
  {
    id: "marukyu-koyamaen-uji",
    name: "Marukyu-Koyamaen",
    city: "Uji",
    country: "Japan",
    lat: 34.8917,
    lng: 135.8067,
    rating: 4.8,
    tagline: "stone-milled uji, zero notes app",
    note: "Stone-ground Uji whispers through the fog of the cup—a small pilgrimage that repays every train stop.",
  },
  {
    id: "nakamura-tokichi-uji",
    name: "Nakamura Tokichi",
    city: "Uji",
    country: "Japan",
    lat: 34.8907,
    lng: 135.8073,
    rating: 4.7,
    tagline: "parfait goals + hojicha side quest",
    note: "Parfait layers and the echo of hojicha frame matcha that tastes like river light held still at noon.",
  },
  {
    id: "cha-cha-matcha-nyc",
    name: "Cha Cha Matcha",
    city: "New York",
    country: "United States",
    lat: 40.7223,
    lng: -73.9943,
    rating: 4.4,
    tagline: "downtown matcha latte core",
    note: "Downtown hum falls away behind a cloud of vivid green that insists the afternoon is still generous.",
    signatureDrink: "Matcha latte",
  },
  {
    id: "matchaful-nyc",
    name: "Matchaful",
    city: "New York",
    country: "United States",
    lat: 40.7287,
    lng: -74.0021,
    rating: 4.6,
    tagline: "west village soft-girl sip",
    note: "West Village calm meets ceremony in a cup that wears its brightness without apology or haste.",
  },
  {
    id: "tombo-london",
    name: "Tombo",
    city: "London",
    country: "United Kingdom",
    lat: 51.4944,
    lng: -0.1745,
    rating: 4.5,
    tagline: "matcha soft serve era",
    note: "South Kensington holds this pocket of Kyoto-soft sweetness where the Thames might as well be the Kamo.",
    signatureDrink: "Matcha soft serve",
  },
  {
    id: "sf-matcha-maiko-japantown",
    name: "Matcha Cafe Maiko",
    city: "San Francisco",
    country: "United States",
    lat: 37.7851,
    lng: -122.4324,
    rating: 4.2,
    tagline: "Japantown",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-matcha-maiko-stonestown",
    name: "Matcha Cafe Maiko",
    city: "San Francisco",
    country: "United States",
    lat: 37.729,
    lng: -122.4765,
    rating: 4.3,
    tagline: "Stonestown",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-kiss-of-matcha",
    name: "Kiss of Matcha",
    city: "San Francisco",
    country: "United States",
    lat: 37.7782,
    lng: -122.4785,
    rating: 4.4,
    tagline: "Richmond District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-stonemill-matcha",
    name: "Stonemill Matcha",
    city: "San Francisco",
    country: "United States",
    lat: 37.7578,
    lng: -122.4212,
    rating: 4.5,
    tagline: "Mission District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-tadaima",
    name: "Tadaima",
    city: "San Francisco",
    country: "United States",
    lat: 37.7613,
    lng: -122.4185,
    rating: 4.6,
    tagline: "Mission District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-third-culture-bakery",
    name: "Third Culture Bakery",
    city: "San Francisco",
    country: "United States",
    lat: 37.7545,
    lng: -122.4692,
    rating: 4.7,
    tagline: "Inner Sunset",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-heytea-union-square",
    name: "HEYTEA",
    city: "San Francisco",
    country: "United States",
    lat: 37.7879,
    lng: -122.4075,
    rating: 4.8,
    tagline: "Union Square",
    note: "Mock listing for map preview — swap in your real notes anytime.",
    signatureDrink: "Supreme Matcha Latte",
  },
  {
    id: "sf-uji-time",
    name: "Uji Time Dessert",
    city: "San Francisco",
    country: "United States",
    lat: 37.784,
    lng: -122.4295,
    rating: 4.2,
    tagline: "Various — near Japantown",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-boba-guys",
    name: "Boba Guys",
    city: "San Francisco",
    country: "United States",
    lat: 37.7596,
    lng: -122.4218,
    rating: 4.3,
    tagline: "Various — Mission sample pin",
    note: "Mock listing for map preview — swap in your real notes anytime.",
    signatureDrink: "Matcha latte",
  },
  {
    id: "sf-asha-tea-house",
    name: "Asha Tea House",
    city: "San Francisco",
    country: "United States",
    lat: 37.7948,
    lng: -122.4025,
    rating: 4.4,
    tagline: "Financial District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-crown-crumpet-ross",
    name: "Crown & Crumpet Tea Stop Café",
    city: "San Francisco",
    country: "United States",
    lat: 37.9624,
    lng: -122.555,
    rating: 4.5,
    tagline: "Ross",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-pinhole-coffee",
    name: "Pinhole Coffee",
    city: "San Francisco",
    country: "United States",
    lat: 37.7432,
    lng: -122.4168,
    rating: 4.6,
    tagline: "Bernal Heights",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-andytown-coffee",
    name: "Andytown Coffee Roasters",
    city: "San Francisco",
    country: "United States",
    lat: 37.7504,
    lng: -122.4989,
    rating: 4.7,
    tagline: "Ocean Beach",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-saint-frank-coffee",
    name: "Saint Frank Coffee",
    city: "San Francisco",
    country: "United States",
    lat: 37.8014,
    lng: -122.4225,
    rating: 4.8,
    tagline: "Russian Hill",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-sightglass-coffee",
    name: "Sightglass Coffee",
    city: "San Francisco",
    country: "United States",
    lat: 37.7786,
    lng: -122.3945,
    rating: 4.2,
    tagline: "SoMa",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-the-mill",
    name: "The Mill",
    city: "San Francisco",
    country: "United States",
    lat: 37.7767,
    lng: -122.4351,
    rating: 4.3,
    tagline: "Alamo Square",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-wrecking-ball-coffee",
    name: "Wrecking Ball Coffee Roasters",
    city: "San Francisco",
    country: "United States",
    lat: 37.797,
    lng: -122.437,
    rating: 4.4,
    tagline: "Cow Hollow",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-ritual-coffee",
    name: "Ritual Coffee Roasters",
    city: "San Francisco",
    country: "United States",
    lat: 37.7565,
    lng: -122.4215,
    rating: 4.5,
    tagline: "Mission District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-four-barrel-coffee",
    name: "Four Barrel Coffee",
    city: "San Francisco",
    country: "United States",
    lat: 37.7615,
    lng: -122.424,
    rating: 4.6,
    tagline: "Mission District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-equator-coffees",
    name: "Equator Coffees",
    city: "San Francisco",
    country: "United States",
    lat: 37.8046,
    lng: -122.4335,
    rating: 4.7,
    tagline: "Fort Mason",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-blue-bottle-ferry",
    name: "Blue Bottle Coffee",
    city: "San Francisco",
    country: "United States",
    lat: 37.7956,
    lng: -122.3935,
    rating: 4.8,
    tagline: "Ferry Building",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-coffee-movement",
    name: "Coffee Movement",
    city: "San Francisco",
    country: "United States",
    lat: 37.793,
    lng: -122.4168,
    rating: 4.2,
    tagline: "Nob Hill",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-snowbird-coffee",
    name: "Snowbird Coffee",
    city: "San Francisco",
    country: "United States",
    lat: 37.7532,
    lng: -122.4675,
    rating: 4.3,
    tagline: "Inner Sunset",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-home-cafe",
    name: "Home Cafe",
    city: "San Francisco",
    country: "United States",
    lat: 37.7548,
    lng: -122.5065,
    rating: 4.4,
    tagline: "Outer Sunset",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-baza",
    name: "Baza",
    city: "San Francisco",
    country: "United States",
    lat: 37.7758,
    lng: -122.3965,
    rating: 4.5,
    tagline: "SoMa",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "sf-fifty-fifty",
    name: "Fifty/Fifty Coffee and Tea",
    city: "San Francisco",
    country: "United States",
    lat: 37.7822,
    lng: -122.4655,
    rating: 4.6,
    tagline: "Richmond District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-tea-master-little-tokyo",
    name: "Tea Master of Little Tokyo",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0506,
    lng: -118.2402,
    rating: 4.2,
    tagline: "Little Tokyo",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-amai-santa-monica",
    name: "Amai",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0215,
    lng: -118.4965,
    rating: 4.3,
    tagline: "Santa Monica · Pico & 17th",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-midori-matcha",
    name: "Midori Matcha",
    city: "Los Angeles",
    country: "United States",
    lat: 34.049,
    lng: -118.2422,
    rating: 4.4,
    tagline: "Little Tokyo",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-tea-drops",
    name: "Tea Drops",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0738,
    lng: -118.2615,
    rating: 4.5,
    tagline: "Echo Park",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-matcha-village",
    name: "Matcha Village",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0428,
    lng: -118.443,
    rating: 4.6,
    tagline: "Sawtelle",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-shuhari-matcha",
    name: "Shuhari Matcha Cafe",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0014,
    lng: -118.4658,
    rating: 4.7,
    tagline: "Abbot Kinney",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-tea-shot",
    name: "Tea Shot",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0674,
    lng: -118.4008,
    rating: 4.8,
    tagline: "Beverly Hills",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-memorylook",
    name: "Memorylook",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0589,
    lng: -118.3018,
    rating: 4.2,
    tagline: "Koreatown",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-motto-tea-cafe",
    name: "Motto Tea Cafe",
    city: "Los Angeles",
    country: "United States",
    lat: 34.1458,
    lng: -118.1505,
    rating: 4.3,
    tagline: "Pasadena",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-maru-coffee",
    name: "Maru Coffee",
    city: "Los Angeles",
    country: "United States",
    lat: 34.1079,
    lng: -118.288,
    rating: 4.4,
    tagline: "Los Feliz",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-alfred-tea-room",
    name: "Alfred Tea Room",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0837,
    lng: -118.3732,
    rating: 4.5,
    tagline: "Melrose Place",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-chacha-matcha",
    name: "Cha Cha Matcha",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0905,
    lng: -118.3725,
    rating: 4.6,
    tagline: "West Hollywood",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-urth-caffe",
    name: "Urth Caffé",
    city: "Los Angeles",
    country: "United States",
    lat: 34.079,
    lng: -118.361,
    rating: 4.7,
    tagline: "Various — Melrose sample pin",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-american-tea-room",
    name: "American Tea Room",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0348,
    lng: -118.2342,
    rating: 4.8,
    tagline: "Arts District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-coffee-tomo",
    name: "Coffee Tomo",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0447,
    lng: -118.4425,
    rating: 4.2,
    tagline: "Sawtelle",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-demitasse",
    name: "Demitasse",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0494,
    lng: -118.241,
    rating: 4.3,
    tagline: "Little Tokyo",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-endorffeine",
    name: "Endorffeine",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0644,
    lng: -118.2384,
    rating: 4.4,
    tagline: "Chinatown",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-go-get-em-tiger",
    name: "Go Get Em Tiger",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0735,
    lng: -118.324,
    rating: 4.5,
    tagline: "Larchmont Village",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-kumquat-coffee",
    name: "Kumquat Coffee",
    city: "Los Angeles",
    country: "United States",
    lat: 34.1101,
    lng: -118.193,
    rating: 4.6,
    tagline: "Highland Park",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-madlab-coffee",
    name: "Madlab Coffee",
    city: "Los Angeles",
    country: "United States",
    lat: 34.1016,
    lng: -118.327,
    rating: 4.7,
    tagline: "Hollywood",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-menottis-coffee",
    name: "Menotti's Coffee Shop",
    city: "Los Angeles",
    country: "United States",
    lat: 33.9957,
    lng: -118.4798,
    rating: 4.8,
    tagline: "Venice",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-nice-coffee",
    name: "Nice Coffee",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0409,
    lng: -118.2572,
    rating: 4.2,
    tagline: "DTLA",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-stereoscope-coffee",
    name: "Stereoscope Coffee",
    city: "Los Angeles",
    country: "United States",
    lat: 34.0758,
    lng: -118.2633,
    rating: 4.3,
    tagline: "Echo Park",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-the-daily-dose",
    name: "The Daily Dose",
    city: "Los Angeles",
    country: "United States",
    lat: 34.035,
    lng: -118.231,
    rating: 4.4,
    tagline: "Arts District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "la-verve-coffee",
    name: "Verve Coffee Roasters",
    city: "Los Angeles",
    country: "United States",
    lat: 34.045,
    lng: -118.2505,
    rating: 4.5,
    tagline: "DTLA",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-matcha-maiko-newbury",
    name: "Matcha Cafe Maiko",
    city: "Boston",
    country: "United States",
    lat: 42.3504,
    lng: -71.0812,
    rating: 4.2,
    tagline: "Newbury Street",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-matcha-maiko-downtown",
    name: "Matcha Cafe Maiko",
    city: "Boston",
    country: "United States",
    lat: 42.3522,
    lng: -71.0552,
    rating: 4.3,
    tagline: "Downtown Boston",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-pavement-coffeehouse",
    name: "Pavement Coffeehouse",
    city: "Boston",
    country: "United States",
    lat: 42.3603,
    lng: -71.0942,
    rating: 4.4,
    tagline: "Various — Back Bay sample",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-tatte",
    name: "Tatte Bakery & Café",
    city: "Boston",
    country: "United States",
    lat: 42.3497,
    lng: -71.0842,
    rating: 4.5,
    tagline: "Various — Back Bay sample",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-thinking-cup",
    name: "Thinking Cup",
    city: "Boston",
    country: "United States",
    lat: 42.3553,
    lng: -71.0658,
    rating: 4.6,
    tagline: "Boston Common",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-ogawa-coffee",
    name: "Ogawa Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.3565,
    lng: -71.059,
    rating: 4.7,
    tagline: "Downtown Crossing",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-george-howell",
    name: "George Howell Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.3625,
    lng: -71.0593,
    rating: 4.8,
    tagline: "Public Market",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-curio-coffee",
    name: "Curio Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.393,
    lng: -71.1225,
    rating: 4.2,
    tagline: "Cambridge",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-broadsheet-coffee",
    name: "Broadsheet Coffee Roasters",
    city: "Boston",
    country: "United States",
    lat: 42.3738,
    lng: -71.1192,
    rating: 4.3,
    tagline: "Cambridge",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-gracenote-coffee",
    name: "Gracenote Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.3503,
    lng: -71.057,
    rating: 4.4,
    tagline: "Leather District",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-render-coffee",
    name: "Render Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.339,
    lng: -71.076,
    rating: 4.5,
    tagline: "South End",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-jp-licks",
    name: "J.P. Licks",
    city: "Boston",
    country: "United States",
    lat: 42.3736,
    lng: -71.1192,
    rating: 4.6,
    tagline: "Various — Harvard Square",
    note: "Mock listing for map preview — swap in your real notes anytime.",
    signatureDrink: "Matcha ice cream",
  },
  {
    id: "bos-pressed-juicery",
    name: "Pressed Juicery",
    city: "Boston",
    country: "United States",
    lat: 42.3516,
    lng: -71.0458,
    rating: 4.7,
    tagline: "Seaport · matcha freezes",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-fomu",
    name: "FoMu",
    city: "Boston",
    country: "United States",
    lat: 42.3541,
    lng: -71.1314,
    rating: 4.8,
    tagline: "Allston · plant-based matcha treats",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-la-colombe-seaport",
    name: "La Colombe Coffee Roasters",
    city: "Boston",
    country: "United States",
    lat: 42.3512,
    lng: -71.0462,
    rating: 4.2,
    tagline: "Seaport",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-blue-bottle-prudential",
    name: "Blue Bottle Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.3458,
    lng: -71.0828,
    rating: 4.3,
    tagline: "Prudential Center",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-kured",
    name: "Kured",
    city: "Boston",
    country: "United States",
    lat: 42.3591,
    lng: -71.071,
    rating: 4.4,
    tagline: "Beacon Hill",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-neighborhood-coffee-roast",
    name: "Neighborhood Coffee Roast",
    city: "Boston",
    country: "United States",
    lat: 42.3176,
    lng: -71.0768,
    rating: 4.5,
    tagline: "Dorchester",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-polcaris-coffee",
    name: "Polcari's Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.3653,
    lng: -71.0548,
    rating: 4.6,
    tagline: "North End",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-reunion-coffee",
    name: "Reunion Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.3414,
    lng: -71.0726,
    rating: 4.7,
    tagline: "South End",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-solstice-coffee",
    name: "Solstice Coffee",
    city: "Boston",
    country: "United States",
    lat: 42.352,
    lng: -71.0458,
    rating: 4.8,
    tagline: "Seaport",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-the-well-coffeehouse",
    name: "The Well Coffeehouse",
    city: "Boston",
    country: "United States",
    lat: 42.3514,
    lng: -71.056,
    rating: 4.2,
    tagline: "South Station",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-vester",
    name: "Vester",
    city: "Boston",
    country: "United States",
    lat: 42.373,
    lng: -71.1172,
    rating: 4.3,
    tagline: "Cambridge",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-wired-puppy",
    name: "Wired Puppy",
    city: "Boston",
    country: "United States",
    lat: 42.3488,
    lng: -71.0858,
    rating: 4.4,
    tagline: "Back Bay",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-zinneken",
    name: "Zinneken's",
    city: "Boston",
    country: "United States",
    lat: 42.3731,
    lng: -71.1186,
    rating: 4.5,
    tagline: "Harvard Square",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "bos-cicada-coffee",
    name: "Cicada Coffee Bar",
    city: "Boston",
    country: "United States",
    lat: 42.365,
    lng: -71.1035,
    rating: 4.6,
    tagline: "Cambridge",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-nakamura-tokichi-ginza",
    name: "Nakamura Tokichi",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6698,
    lng: 139.7646,
    rating: 4.2,
    tagline: "Ginza SIX",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-suzukien",
    name: "Suzukien",
    city: "Tokyo",
    country: "Japan",
    lat: 35.7149,
    lng: 139.7965,
    rating: 4.3,
    tagline: "Asakusa · intense matcha gelato",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-zen-punk-matcha",
    name: "ZEN PUNK MATCHA",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6712,
    lng: 139.764,
    rating: 4.4,
    tagline: "Ginza",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-capoon-shimokitazawa",
    name: "CAPOON Matcha Seizojo",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6619,
    lng: 139.6678,
    rating: 4.5,
    tagline: "Shimokitazawa",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-yunomi-cafe",
    name: "Yunomi Cafe",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6204,
    lng: 139.7008,
    rating: 4.6,
    tagline: "Musashi-Koyama",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-cha-no-wa-tokyo",
    name: "Cha-no-wa TOKYO",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6814,
    lng: 139.7673,
    rating: 4.7,
    tagline: "Tokyo Station",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-jugetsudo-ginza",
    name: "Jugetsudo",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6696,
    lng: 139.7671,
    rating: 4.8,
    tagline: "Ginza · Kabukiza Theater",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-atelier-matcha",
    name: "ATELIER MATCHA",
    city: "Tokyo",
    country: "Japan",
    lat: 35.671,
    lng: 139.7652,
    rating: 4.2,
    tagline: "Ginza",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-ippuku-matcha",
    name: "IPPUKU & MATCHA",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6842,
    lng: 139.7736,
    rating: 4.3,
    tagline: "Nihonbashi",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-the-matcha-tokyo",
    name: "THE MATCHA TOKYO",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6649,
    lng: 139.7063,
    rating: 4.4,
    tagline: "Omotesandō",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-matcha-lab-ueno",
    name: "Matcha Lab",
    city: "Tokyo",
    country: "Japan",
    lat: 35.7119,
    lng: 139.7737,
    rating: 4.5,
    tagline: "Ueno Marui",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-ippodo-marunouchi",
    name: "Ippodo Tea",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6825,
    lng: 139.7647,
    rating: 4.6,
    tagline: "Marunouchi",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-hatoya-shibuya",
    name: "Hatoya Ryoyousha",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6597,
    lng: 139.6991,
    rating: 4.7,
    tagline: "Shibuya",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-uji-no-kura",
    name: "Uji no Kura",
    city: "Tokyo",
    country: "Japan",
    lat: 35.7152,
    lng: 139.7932,
    rating: 4.8,
    tagline: "Asakusa",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-cafe-kitsune-aoyama",
    name: "Café Kitsuné",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6647,
    lng: 139.7085,
    rating: 4.2,
    tagline: "Aoyama",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-saryo-tsujiri",
    name: "Saryo Tsujiri",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6854,
    lng: 139.7712,
    rating: 4.3,
    tagline: "Daimaru Tokyo",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-hibiya-hayashiya",
    name: "Hibiya Hayashiya Shinbei",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6725,
    lng: 139.7592,
    rating: 4.4,
    tagline: "Hibiya Midtown",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-matcha-stand-maruni",
    name: "Matcha Stand Maruni",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6656,
    lng: 139.7758,
    rating: 4.5,
    tagline: "Tsukiji",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-kosoan",
    name: "Kosoan",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6077,
    lng: 139.6685,
    rating: 4.6,
    tagline: "Jiyūgaoka",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-saten-japanese-tea",
    name: "Satén Japanese Tea",
    city: "Tokyo",
    country: "Japan",
    lat: 35.704,
    lng: 139.5998,
    rating: 4.7,
    tagline: "Nishi-Ogikubo",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-tea-buck",
    name: "Tea Buck",
    city: "Tokyo",
    country: "Japan",
    lat: 35.651,
    lng: 139.705,
    rating: 4.8,
    tagline: "Daikanyama",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-sakurai-tea",
    name: "Sakurai Tea Experience",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6652,
    lng: 139.7205,
    rating: 4.2,
    tagline: "Minami-Aoyama",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-toraya-aoyama",
    name: "Toraya Café",
    city: "Tokyo",
    country: "Japan",
    lat: 35.666,
    lng: 139.7158,
    rating: 4.3,
    tagline: "Aoyama",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-kabi-meguro",
    name: "Kabi",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6414,
    lng: 139.6984,
    rating: 4.4,
    tagline: "Meguro",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },
  {
    id: "tyo-no-502",
    name: "No. 502",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6437,
    lng: 139.6532,
    rating: 4.5,
    tagline: "Setagaya",
    note: "Mock listing for map preview — swap in your real notes anytime.",
  },

];
