/**
 * Famous / notable ceremonial matcha for the collection page.
 * Edit ratings and notes freely — loaded as a classic script.
 */
window.MATCHA_TINS = [
  {
    id: 'ippodo-sayaka',
    name: 'Sayaka no Mukashi',
    producer: 'Ippodo · Kyoto',
    rating: 4.9,
    note: 'Bright, silky, almost buttery — my gold standard for quiet mornings.',
    tinColor: '#5a8f4a',
    lidColor: '#d4bc7a',
  },
  {
    id: 'marukyu-aoarashi',
    name: 'Aoarashi',
    producer: 'Marukyu-Koyamaen · Uji',
    rating: 4.8,
    note: 'Deep umami, barely any bitterness when whisked soft. Worth the splurge.',
    tinColor: '#4d7c3c',
    lidColor: '#c9a85c',
  },
  {
    id: 'ippodo-ikuyo',
    name: 'Ikuyo',
    producer: 'Ippodo · Kyoto',
    rating: 4.7,
    note: 'Friendly everyday ippodo — grassy, sweet finish, forgives sloppy whisking.',
    tinColor: '#6b9e52',
    lidColor: '#e0c88a',
  },
  {
    id: 'naoki-superior',
    name: 'Superior Organic',
    producer: 'Naoki Matcha',
    rating: 4.6,
    note: 'Clean organic profile; lighter body but gorgeous color in the bowl.',
    tinColor: '#5f8b48',
    lidColor: '#b8956b',
  },
  {
    id: 'ippodo-ummon',
    name: 'Ummon',
    producer: 'Ippodo · Kyoto',
    rating: 4.5,
    note: 'Robust and a touch more astringent — wakes you up before email.',
    tinColor: '#4a6b38',
    lidColor: '#c4a86a',
  },
  {
    id: 'encha-ceremonial',
    name: 'Ceremonial Grade',
    producer: 'Encha',
    rating: 4.3,
    note: 'Latte-friendly but still honest as usucha; great gateway tin.',
    tinColor: '#6d8848',
    lidColor: '#d1b978',
  },
  {
    id: 'jade-leaf-ceremonial',
    name: 'Ceremonial Matcha',
    producer: 'Jade Leaf Organics',
    rating: 4.0,
    note: 'Supermarket hero — not subtle, but reliable and easy to find.',
    tinColor: '#5c7a45',
    lidColor: '#a89262',
  },
  {
    id: 'golde-pure',
    name: 'Pure Matcha',
    producer: 'Golde',
    rating: 4.2,
    note: 'Mellow, slightly creamy; blends beautifully into oat milk.',
    tinColor: '#719456',
    lidColor: '#bf9e6e',
  },
  {
    id: 'ippodo-kanza',
    name: 'Kanza',
    producer: 'Ippodo · Kyoto',
    rating: 4.4,
    note: 'Vegital edge and long finish — for days you want matcha to taste like matcha.',
    tinColor: '#4f6f3e',
    lidColor: '#c9b06a',
  },
  {
    id: 'mizuba-daily',
    name: 'Daily Matcha',
    producer: 'Mizuba Tea Co.',
    rating: 4.6,
    note: 'Stone-milled smoothness; my “I deserve nice things Tuesday” tin.',
    tinColor: '#578244',
    lidColor: '#dcc18a',
  },
];
