/**
 * Favorite matcha spots for the map. Edit freely.
 * Loaded as a classic script so window.MATCHA_PLACES is available globally.
 */
window.MATCHA_PLACES = [
  {
    id: "ippodo-kyoto",
    name: "Ippodo Tea",
    city: "Kyoto",
    country: "Japan",
    lat: 35.0116,
    lng: 135.7681,
    rating: 4.9,
    note: "Centuries of ritual seem to steep in every bowl, as though the city’s quiet dignity had been whisked into green foam.",
    signatureDrink: "Usucha",
  },
  {
    id: "marukyu-koyamaen-uji",
    name: "Marukyu-Koyamaen",
    city: "Uji",
    country: "Japan",
    lat: 34.8917,
    lng: 135.8067,
    rating: 4.8,
    note: "Stone-ground Uji whispers through the fog of the cup—a small pilgrimage that repays every train stop.",
  },
  {
    id: "nakamura-tokichi-uji",
    name: "Nakamura Tokichi",
    city: "Uji",
    country: "Japan",
    lat: 34.8907,
    lng: 135.8073,
    rating: 4.7,
    note: "Parfait layers and the echo of hojicha frame matcha that tastes like river light held still at noon.",
  },
  {
    id: "cha-cha-matcha-nyc",
    name: "Cha Cha Matcha",
    city: "New York",
    country: "United States",
    lat: 40.7223,
    lng: -73.9943,
    rating: 4.4,
    note: "Downtown hum falls away behind a cloud of vivid green that insists the afternoon is still generous.",
    signatureDrink: "Matcha latte",
  },
  {
    id: "matchaful-nyc",
    name: "Matchaful",
    city: "New York",
    country: "United States",
    lat: 40.7287,
    lng: -74.0021,
    rating: 4.6,
    note: "West Village calm meets ceremony in a cup that wears its brightness without apology or haste.",
  },
  {
    id: "tombo-london",
    name: "Tombo",
    city: "London",
    country: "United Kingdom",
    lat: 51.4944,
    lng: -0.1745,
    rating: 4.5,
    note: "South Kensington holds this pocket of Kyoto-soft sweetness where the Thames might as well be the Kamo.",
    signatureDrink: "Matcha soft serve",
  },
];
